services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - sqlite_data:/data
    depends_on:
      - db
    environment:
      - DATABASE_URL=sqlite:///data/database.db

  db:
    image: alpine/sqlite:latest
    volumes:
      - sqlite_data:/data
    command: >
      sh -c "apk add --no-cache sqlite &&
             mkdir -p /data &&
             sqlite3 /data/database.db 'CREATE TABLE IF NOT EXISTS test (id INTEGER PRIMARY KEY, name TEXT);' &&
             sqlite3 /data/database.db 'SELECT sqlite_version();'"
    healthcheck:
      test: [ "CMD", "sqlite3", "/data/database.db", "SELECT 1;" ]
      interval: 5s
      timeout: 2s
      retries: 3

volumes:
  sqlite_data:
